### ISSUE TITLE
Multiple profiles

### ISSUE THREAD

**Issue by dianacordun** [florea-alex/FindAStudyBuddy#4]
Multiple profiles can be created and added to the database for the same user. The relationship between user and profile should be one-to-one.

**Comment by AndrewSSB** [comment]
Fixed by checking everytime if the user with the input ID has already a profile, if so he can't create another one.

**Comment by AndrewSSB** [comment]
public async Task Create(ProfilePostModel model, int userId)
        {
            var user = await _context.Users.FirstOrDefaultAsync(x => x.Id == userId);

            if (user == null) { throw new KeyNotFoundException($"There is no user with id {userId}"); }

            if (user.ProfileId != null) { throw new Exception("There's aleady a profile created for this user, you can update it"); } //here is the solution

            var profile = _mapper.Map<UserProfile>(model);

            user.ProfileId = profile.Id;
            //user.Profile = profile;
            profile.User = user;
            await _context.AddAsync(profile);
            await _context.SaveChangesAsync();
        }
