### ISSUE TITLE
Matching algorithm problem

### ISSUE THREAD

**Issue by florea-alex** [florea-alex/FindAStudyBuddy#6]
Matching algorithm takes all users and does not respect the required rules (should match users based on the courses one needs/offers help with the other users who offer/need help on the same courses, but should not match user X with himself/herself).

**Comment by AndrewSSB** [comment]
Fixed by doing some selection:
- first, select all users except for myself and my friends
- second, select all my courses details
- third, select from FIRST selection all users that have atleast 1 course in common with me

And in the end for each user in the third selection check if there's ANY course that respects our criteria (if i need help with POO and the current user OFFERS help with POO we add him in the suggestion list)


            //get all my friends
            var friends = await _appDbContext.UserConnections.Where(x => x.UserId == user.Id).ToListAsync();

            //get all users except my self and my friends
            IQueryable<User> users = _appDbContext.Users.Where(x => x.Id != user.Id && !x.UserConnections.Any(y => y.UserId == user.Id)); 

            //get my courses
            var courses = await _appDbContext.Courses.Where(x => x.ProfileId == user.ProfileId).ToListAsync();
            var coursesName = courses.Select(x => x.courseName).ToList();

            //now im getting users based on my courses
            var _users = await users.Include(x => x.Profile).Where(x => x.Profile.Courses.Any(y => coursesName.Contains(y.courseName))).ToListAsync();

            var response = new List<int>();

            foreach (var _user in _users) //now check for each user if they respect our criteria
            {
                var userCourses = await _appDbContext.Courses.Where(x => x.ProfileId == _user.ProfileId).ToListAsync();
                foreach (var userCourse in userCourses)
                {
                    var helper = courses.FirstOrDefault(x => x.courseName == userCourse.courseName && x.Helper != userCourse.Helper);
                    if (helper != null)
                        response.Add(_user.Id);
                }
            }
            
            return response.Distinct().ToList();
