### ISSUE TITLE
Matching algorithm connection issue

### ISSUE THREAD

**Issue by florea-alex** [florea-alex/FindAStudyBuddy#7]
If user X swipes user Y as their friend, but user Y does not have user X as a connection yet (maybe they didn't find user X in their list yet or they swiped left on user X). Then user X shouldn't have user Y in their friends list/connection list.

**Comment by AndrewSSB** [comment]
Fixed by adding a new column in our database named FriendId and when AddFriend endpoint is called with UserId and FriendId we add FriendId as UserId friend, but also to FriendId we add UserId as friend.

        public async Task<string> AddFriend(AddFriendModel model)
        {
            if (model.FriendId == model.UserId)
                throw new Exception("Can't add yourself as a friend you weirdo");

            if (await _context.UserConnections.AnyAsync(x => x.UserId == model.UserId && x.FriendId == model.FriendId))
                throw new Exception("You already have this friend");

            var user = await _context.Users.FirstOrDefaultAsync(x => x.Id == model.UserId);
            var friend = await _context.Users.FirstOrDefaultAsync(x => x.Id == model.FriendId);

            if (user == null || friend == null)
                throw new Exception("You/your friend does not exists");

            var friend1 = new UserConnections
            {
                UserId = model.UserId,
                FriendId = model.FriendId,
                User = user
            };

            var friend2 = new UserConnections
            {
                UserId = model.FriendId,
                FriendId = model.UserId,
                User = friend
            };

            await _context.UserConnections.AddAsync(friend1);
            user.UserConnections.Add(friend1);
            await _context.UserConnections.AddAsync(friend2);
            friend.UserConnections.Add(friend2);

            await _context.SaveChangesAsync();

            return "Friend added succesfully";
        }
